# Generated by Django 4.2.13 on 2025-11-30 10:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('roll_number', models.CharField(default='Unknown', max_length=20, unique=True)),
                ('branch', models.CharField(default='Unknown', max_length=100)),
                ('no_show_count', models.IntegerField(default=0)),
                ('last_penalty_date', models.DateTimeField(blank=True, null=True)),
                ('is_restricted', models.BooleanField(default=False)),
                ('fines', models.DecimalField(decimal_places=2, default=0.0, help_text='Outstanding fines in rupees', max_digits=10)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Compartment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveIntegerField(unique=True)),
                ('is_empty', models.BooleanField(default=True)),
                ('otp_expiration', models.DateTimeField(blank=True, null=True)),
                ('student', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='compartments.student')),
            ],
        ),
        migrations.CreateModel(
            name='OTP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=6)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('generated_at', models.DateTimeField()),
                ('compartment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='compartments.compartment')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='compartments.student')),
            ],
            options={
                'indexes': [models.Index(fields=['student'], name='compartment_student_0698c1_idx'), models.Index(fields=['code'], name='compartment_code_bbeafc_idx')],
            },
        ),
    ]
