# Generated by Django 4.2.13 on 2025-11-30 10:40

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('compartments', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LibrarySettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('max_booking_duration', models.IntegerField(default=180, help_text='Maximum booking duration in minutes', validators=[django.core.validators.MinValueValidator(30), django.core.validators.MaxValueValidator(720)])),
                ('max_advance_booking_days', models.IntegerField(default=1, help_text='Maximum days in advance a booking can be made', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(30)])),
                ('check_in_buffer', models.IntegerField(default=15, help_text='Minutes allowed for check-in after reservation start', validators=[django.core.validators.MinValueValidator(5), django.core.validators.MaxValueValidator(60)])),
                ('max_active_reservations', models.IntegerField(default=1, help_text='Maximum number of active reservations per user', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('penalty_threshold', models.IntegerField(default=3, help_text='Number of no-shows before penalties apply')),
                ('penalty_duration_days', models.IntegerField(default=7, help_text='Number of days user is restricted after exceeding threshold')),
            ],
            options={
                'verbose_name_plural': 'Library Settings',
            },
        ),
        migrations.CreateModel(
            name='Seat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=10, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('description', models.CharField(blank=True, max_length=200)),
                ('location', models.CharField(blank=True, max_length=50)),
            ],
            options={
                'indexes': [models.Index(fields=['is_active'], name='reservation_is_acti_d55564_idx')],
            },
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('status', models.CharField(choices=[('reserved', 'reserved'), ('checked_in', 'checked_in'), ('cancelled', 'cancelled'), ('completed', 'completed'), ('no_show', 'no_show')], default='reserved', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('check_in_time', models.DateTimeField(blank=True, null=True)),
                ('otp', models.CharField(blank=True, max_length=6, null=True)),
                ('otp_generated_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('seat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reservations.seat')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='compartments.student')),
            ],
            options={
                'ordering': ['-start_time'],
                'indexes': [models.Index(fields=['student'], name='reservation_student_1c05a6_idx'), models.Index(fields=['seat'], name='reservation_seat_id_761526_idx'), models.Index(fields=['status'], name='reservation_status_f1a03a_idx'), models.Index(fields=['start_time'], name='reservation_start_t_f3e5cd_idx'), models.Index(fields=['end_time'], name='reservation_end_tim_c11544_idx'), models.Index(fields=['student', 'status', 'end_time'], name='reservation_student_be6772_idx')],
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, help_text='Amount paid in rupees', max_digits=10)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('stripe_session_id', models.CharField(blank=True, max_length=255, null=True)),
                ('stripe_payment_intent_id', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='compartments.student')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['student', 'status'], name='reservation_student_331717_idx'), models.Index(fields=['stripe_session_id'], name='reservation_stripe__23a670_idx')],
            },
        ),
    ]
